[theme]
base = "dark"
primaryColor = "#6FA6A5"
backgroundColor = "#101A1C"
secondaryBackgroundColor = "#17272A"
textColor = "#E7EFEE"
font = "sans serif"

[server]
maxUploadSize = 5
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"